title: Test site
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:" It will appear in your document head meta (for Google search results) and in your feed.xml site description. 
  Trying out Github Pages. 

# social links
twitter_username: tomomiq
github_username:  tomomiq

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
